### ISSUE TITLE
[Feature] Use Adjacent Leaves Check Tree

### ISSUE THREAD

**Issue by darksaid98** [Norbit4/TreeCuter#12]
Hey! Thanks for this most excellent plugin in a sea of barely supported and outdated tree-cutting plugins.

I'm asking for a quite significant feature to be added here, Although the current configuration is simple, there is a drawback to this simplicity. If you build a wall out of logs, accidentally cutting it down is not that difficult (_especially for a player with let's say a beacon & fully enchanted axe nearby_), even with shift protection enabled. 

The problem stems from the fact that any collection of logs connected is detected as a tree. I propose you count adjacent leaves to the log to determine if it is a tree.

If the configuration was reworked like such:
```yaml
tree-types:
  oak:
    wood-blocks:
      - 'OAK_LOG'
    leaf-blocks:
      - 'OAK_LEAVES'
    min-leaves: 10 # Without 10 of the leaf-blocks adjacent to the wood-blocks, it cannot be this tree type
  some-custom-tree:
    wood-blocks:
      - 'OAK_LOG'
      - 'STRIPPED_BIRCH_WOOD'
    leaf-blocks:
      - 'OAK_LEAVES'
      - 'CHERRY_LEAVES'
    min-leaves: -1
```

It would make the plugin much more configurable and allow users to also define custom trees. In the future it would also be easy to extend the system to allow more tree detection criteria.
